## Filebeat configuration
## https://github.com/elastic/beats/blob/master/deploy/docker/filebeat.docker.yml
#

filebeat.inputs:
  - type: log
    paths:
      - /logdatadir/access*.log
output.logstash:
  hosts: ["logstash:5044"]

http.enabled: true
http.host: 0.0.0.0
